kind: pipeline
name: build

type : docker

volumes:
  - name: m2cache
    host:
      path: /var/cache/m2cache
steps:

  - name: test
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DATASOURCE_DRIVER: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://db:5432/sa_test_db
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
      SONAR_HOST :
        from_secret : SONAR_HOST
      SONAR_TOKEN :
        from_secret : SONAR_TOKEN
    commands:
      - rm -rf /root/.m2/repository/org/ujar/
      - mvn compile test-compile com.github.spotbugs:spotbugs-maven-plugin:check pmd:check -Dspotbugs.xmlOutput=true -Dspotbugs.failOnError=false -Dspotbugs.includeTests=true -B -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=ujar-org:basics-rest-user-profile-crud -Dsonar.projectName=ujar-org:basics-rest-user-profile-crud --batch-mode -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: publish-snapshot-package
    depends_on :
      - test
    image: maven:3-openjdk-17-slim
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: publish-release-package
    depends_on :
      - test
    image: maven:3-openjdk-17-slim
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -s settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
    when:
      event: tag

  - name: docker-build-dev-image
    depends_on :
      - publish-snapshot-package
    image: plugins/docker
    settings:
      dockerfile: src/main/docker/Dockerfile
      context: ./
      storage_driver: vfs
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: docker-registry.ujar.org/ujar/basics-rest-user-profile-crud
      registry: docker-registry.ujar.org
      tags :
        - latest
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

services:
  - name: db
    image: postgres:13.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sa_test_db
